version: '3.8'

services:
  cyberchef-server:
    image: khulnasoft/intelx_cyberchef:${REACT_APP_INTELX_VERSION}
    container_name: intelx_cyberchef
    restart: unless-stopped
    expose:
      - '3000'
    depends_on:
      - uwsgi
