# IMPORTANT: The version must match the version of docker-compose.yml
---
version: '3.8'

# All additional integrations should be added following this format only.

services:
  tor_analyzers:
    image: khulnasoft/intelx_tor_analyzers:${REACT_APP_INTELX_VERSION}
    container_name: intelx_tor_analyzers
    restart: unless-stopped
    expose:
      - "4001"
    env_file:
      - env_file_integrations
    volumes:
      - generic_logs:/var/log/intel_x
    depends_on:
      - uwsgi
